# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Denis Shvetsov
title: Systems Architect
email: denis.shvetsov.me@gmail.com
website: https://betterthanever2.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  betterthanever2
linkedin_username: denis-shvetsov

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
gtag: "G-KEPGYKHP3W"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Denis. Thank you for visiting my page.
  
  I am an aspiring systems architect. "Aspiring" means that most of my experience was accumulated outside my direct work responsibilities: 
  I built a complex system almost entirely on my own specifically as a means of ascending to the architect's level. See "Proof of skill" for details.
  In addition to various technical skills, I developed mental flexibility and technical intuition that allow me to select best tools for any 
  task regardless of prior experience.

  > I started advancing myself **before** the LLM upheaval, so my skills are solid. I do use LLMs in my day-to-day, but I learned to do it with caution.

  I am best at: <mark>NATS</mark>, <mark>Python</mark>, <mark>databases</mark>, <mark>systemic thinking</mark>

content:
  - title: Core competencies
    layout: list-pane
    content:
      - title: blabla
        set: blabla
        description: blabla
      - title: blabla
        set: blabla
        description: blabla
  
  - title: Tools
    layout: list-pane
    content:
      - title: TOGAF
        set: System Architecture
        description: Industry standard for developing and maintaining enterprise architectures
      - title: OpenTelemetry
        set: System Architecture
        description: Cross-service observability and tracing
      - title: NATS
        set: System Architecture
        description: Framework for building event-driven architectures
      - title: Docker
        set: System Architecture
        description: Conteinerization mechanism
      - title: Kubernetes
        set: System Architecture
        description: Deployment system
      - title: Redis
        set: System Architecture
        description: General-purpose key-value storage
      - title: Microservices
        set: System Architecture
        description: Approach to building applications with restricted responsibilities
      - title: Independent Hosting
        set: System Architecture
        description: Because I would rather avoid giant corporations
      - title: AWS
        set: System Architecture
        description: Because oftentimes giant corporations are unavoidable
      - title: AsyncAPI
        set: System Architecture
        description: Spec for planning and describing async architectures
      - title: git
        set: System Architecture
        description: Best version control
      - title: scripting
        set: Python
        description: Almost any problem could be solved by writing a script
      - title: uv
        set: Python
        description: It's really as fast as advertised
      - title: FastAPI
        set: Python
        description: Superior Python framework for HTTP-based apps
      - title: Pydantic
        set: Python
        description: Types, serialization, deserialization
      - title: sqlalchemy
        set: Python
        description: A starship of database-related work
      - title: sqlmodel
        set: Python
        description: Child of Pydantic & Sqlalchemy
      - title: PostgreSQL
        set: Databases
        description: Best DB for most cases
      - title: SQLite
        set: Databases
        description: Best DB for simple cases and local development
      - title: MongoDB
        set: Databases
        description: Don't like it but sometimes it's necessary
      - title: sql
        set: Data Analysis
        description: Super powerful query language
      - title: pandas
        set: Data Analysis
        description: Data analysis
      - title: Google Sheets
        set: Data Analysis
        description: Sometimes it's just good enough
      - title: array formulas
        set: Data Analysis
        description: These could get pretty complex
      - title: Linux
        set: Tinkering
        description: Because others are too restrictive
      - title: Hyprland
        set: Tinkering
        description: Is convenient to work in
      - title: Jira & Confluence
        set: Business Analysis
        description: I also have experience with other similar systems
      - title: UML & BPMN
        set: Business Analysis
        description: Flows, sequences, charts, etc.
      - title: BABOK
        set: Business Analysis
        description: Business analysis industry standard

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CompStak
        link: compstak.com
        link_text: CompStak
        sub_title: Senior Technical Writer
        caption: July 2020 - Present
        description: | # this will include new lines to allow paragraphs
            At CompStak I am working on setting up a consistent documentation process, as well as maintaining day-to-day documentation activities and assisting with knowledge sharing.
      - layout: left
        title: StageRoll
        sub_title: Business analyst
        caption: December 2020 - April 2021
        description: | # this will include new lines to allow paragraphs
            At StageRoll I was working on the discovery stage of a new product development \- preparation for PoC, MVP and further stages of the development pretty much simultaneously. This included diagrams of various kinds, written documentation and oral communication of knowledge to other members of the team
      - layout: left
        title: Giggster
        sub_title: Data analysis & visualization specialist
        caption: November 2020 - August 2021
        description: | # this will include new lines to allow paragraphs
            In my 2nd iteration with Giggster I was working on the data accumulation and analysis project \- basically a custom ETL in its own right \- with a data visualization module (Python \+ Plotly \+ Dash) as its ultimate outlet.
      - layout: left
        title: Business Process Technology
        sub_title: Business analyst
        caption: June 2020 - January 2021
        description: | # this will include new lines to allow paragraphs
            At BPT I was working on several projects, including in-house products, but mostly on the crypto-currency exchange Exchanger.ee, which I led from conception and almost to release. My responsibilities included elaboration of user stories and business use cases, mockup creation, documentation maintenance, requirements clarification etc.
      - layout: left
        title: Giggster
        sub_title: Business analyst
        caption: March 2016 - November 2019
        description: | # this will include new lines to allow paragraphs
            With Giggster my responsibilities included monitoring of the market (benchmark analysis); research of various aspects of the business operation; integration of the 3rd-party data into the system; writing technical documentation, including user stories and use cases; composing diagrams in UML notation; creating mockups; conducting interviews/maintaining relationships with stakeholders of different levels; etc. 
      - layout: left
        title: Postindustria / Jobjet
        sub_title: Business analyst
        caption: March 2016 - November 2019
        description: | # this will include new lines to allow paragraphs
            In February of 2016 I started collaborating as a business analyst on several projects at Postindustria; mostly on *Jobjet* and *Giggster*, two flagship products of the company. Here I sourced and procured quality databases for enrichment of the operational DBs; hired freelancers for particular sub-projects and managed their activity; coordinated active communications between different stakeholders within the company, as well as external ones; wrote technical documentation; etc.
      - layout: left
        title: IQRIA
        sub_title: Business analyst | Technical writer
        caption: January 2015 - February 2016
        description: | # this will include new lines to allow paragraphs
            I was hired as a technical writer first, but soon enough the spectre of my responsibilities expanded to include mock-ups & wireframe design, communication with customers, as well as research of various aspects of business processes, and other stuff related to the product development activities.
      - layout: left
        title: Moscow Translations Center
        sub_title: Head of Translation Office
        caption: March 2011 - June 2014
        description: | # this will include new lines to allow paragraphs
            During my work at the Moscow Translation Center I managed one of the translations offices in the city of Korolyov, Moscow region. Besides making sure that my office is working properly at all times, my responsibilities included actually performing the translations, keeping close contact with notary public, maintaining communications with a wide circle of freelance translators, and regular financial reporting.

  - title: Proof of Skill
    layout: text
    content: |
      I build 1 project titled "Wapaganda". Its purpose is to collect, clean, and analyze data around a _certain geographical slice_* of the media landscape.

      As of January 2026 the implementation consists of 12 applications (including dedicated orchestrator and data hub) that co-exist in the NATS-based system, 
      with 9+ distinct cross-service flows among them. Technologies employed include website crawling (with and without LLMs), machine learning experiments 
      (MLflow), OTel, HTTP endpoints with FastAPI, Telegram bots, various API integrations, as well as LLM-based determination of relevance (CrewAI).

      The code is located [here](https://github.com/subjective-agency/wapatools), but you would need an explicit invitation to see it. Apologies for this
      extra step, but it's necessary for now*.
      
      *Details on request

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kiev Slavonic University
        caption: 2001 - 2006
        sub_title: Master's degree in International Relations
        description: | # this will include new lines to allow paragraphs
          This was a minor establishment that, however, provided solid foundation in history and generic social sciences. First two years 
          I spent in Mykolaiv, in a local offshoot of the Uni, and in 2003 I moved to Kyiv to continue education. I recieved bachelor's 
          degree in 2005, and master's - a year later. 

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      - layout: left
        title: Russian State University of Cinema in Moscow
        caption: 2006 - 2008
        description: | # this will include new lines to allow paragraphs
          I spent 2 years studying cinema in the workshop by Sergei Solovyov & Valery Rubinchik (both - practicing film directors), and only 
          quit due to lack of funding. I enrolled because I love movies, and always had a thing for writing. Though it didn't work out for me,
          I did acquire a number of foundational skills, and a few life-long friends.

  - title: Broader Context
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Modern Ukrainian poetry
      - Logic puzzles
      - Heavy metal music

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
